import { Josefin_Sans, Libre_Franklin } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import MenuProvider from "@/context/MenuContext";
import CartProvider from "@/context/CartContext";
import ProviderPostUser from "./_component/ProviderPostUser";
import ProductProvider from "@/context/ProductContext";
import OrderProvider from "@/context/OrderContext";
import Menu from "./_component/header/Menu";
import FixedArrow from "./_component/FixedArrow";
import Cart from "./_component/Cart";
import Header from "./_component/header/Header";
import Footer from "./_component/footer/Footer";
import UserProvider from "@/context/UserContext";
import WhislistProvider from "@/context/WhislistContext";

const libre = Libre_Franklin({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "600", "700", "900"],
  variable: "--font-libre",
});
const josefin = Josefin_Sans({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "600", "700"],
  variable: "--font-josefin",
});
export const metadata = {
  title: "Mobilex",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${libre.variable} ${josefin.variable} antialiased`}>
        <ClerkProvider>
          <UserProvider>
            <CartProvider>
              <WhislistProvider>
                <MenuProvider>
                  <ProductProvider>
                    <OrderProvider>
                      <ProviderPostUser>
                        <Menu />
                        <Cart />
                        <Header />
                        <FixedArrow />
                        <main>{children}</main>
                        <Footer />
                      </ProviderPostUser>
                    </OrderProvider>
                  </ProductProvider>
                </MenuProvider>
              </WhislistProvider>
            </CartProvider>
          </UserProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
